### ISSUE TITLE
Update neos/welcome flow dependency version on branching

### ISSUE THREAD

**Issue by albe** [neos/flow-development-distribution#46]

**Comment by kdambekalns** [comment]
How should it be updated? `neos/welcome` isn't branched automatically, so expanding it's allowed range of `neos/flow` might be the right thing to do?

**Comment by albe** [comment]
I noticed that welcome didn't receive the 7.0 branch, but it should according to the script (https://github.com/neos/flow-development-distribution/blob/master/Build/create-branch.sh#L43) - so maybe we need to fix that first?

**Comment by kdambekalns** [comment]
Looks good, no?

https://jenkins.neos.io/job/flow-create-branch/lastSuccessfulBuild/console

```
10:59:06 + cd Packages/Application/Neos.Welcome
10:59:06 + git checkout -b 7.0 origin/master
10:59:06 Switched to a new branch '7.0'
10:59:06 Branch '7.0' set up to track remote branch 'master' from 'origin'.
10:59:06 + cd -
10:59:06 /var/lib/jenkins/workspace/flow-create-branch
10:59:06 + push_branch 7.0 Packages/Application/Neos.Welcome
10:59:06 + local BRANCH=7.0
10:59:06 + local DIR=Packages/Application/Neos.Welcome
10:59:06 + '[' -z Packages/Application/Neos.Welcome ']'
10:59:06 + git --git-dir Packages/Application/Neos.Welcome/.git push origin 7.0
10:59:10 remote: 
10:59:10 remote: Create a pull request for '7.0' on GitHub by visiting:        
10:59:10 remote:      https://github.com/neos/flow-welcome/pull/new/7.0        
10:59:10 remote: 
10:59:10 To github.com:neos/flow-welcome.git
10:59:10  * [new branch]      7.0 -> 7.0
```

**Comment by kdambekalns** [comment]
@bwaidelich You created https://github.com/neos/flow-welcome/commit/6feb43a2ee7ca077e56a5e0982d973276e079228#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34 manually, right?

**Comment by bwaidelich** [comment]
> You created neos/flow-welcome@6feb43a#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34 manually, right?

yes..

**Comment by albe** [comment]
> 10:59:10 To github.com:neos/flow-welcome.git
10:59:10  * [new branch]      7.0 -> 7.0

Interesting, because there definitely is no 7.0 branch on the welcome repo. 🤷‍♂️ Let's just manually branch that off for now and try to solve the automatism for the next release

**Comment by albe** [comment]
done
