### ISSUE TITLE
Order changelog by prefix labels

### ISSUE THREAD

**Issue by albe** [neos/flow-development-distribution#48]
Currently, the changelogs are created in the order of the merges. However, from a user perspective, having the changelog entries grouped by type (feature, bugfix, task/other) would make much more sense.

Can we somehow sort the entries?

**Comment by kdambekalns** [comment]
While collecting them, put the etries into an array per group? Not something I personally would like to do in a shell script, but we can use PHP or even Go instead. 😎

**Comment by albe** [comment]
Yeah, I was taking a look at the shell script and it hurts my head trying to solve this problem there. Would be super easy in a PHP script with something like this:
```
$orderedMessages = ['!!!\s*FEATURE' => [], 'FEATURE' => [], '!!!\s*BUGFIX' => [], 'BUGFIX' => [], '!!!\s*TASK' => [], 'TASK' => []];
...
foreach (array_keys($orderedMessages) as $titlePrefix) {
   if (preg_match('/'.$titlePrefix.'/', $pr['title']) !== false) {
      $orderedMessages[$titlePrefix][] = $extractedDescription;
      break;
   }
}
...
$messages = array_merge(...array_values($orderedMessages));
```
But that means completely rewriting all the other logic first

**Comment by albe** [comment]
There you go :)
