### ISSUE TITLE
Psalm update needed for PHP8 features

### ISSUE THREAD

**Issue by kdambekalns** [neos/flow-development-distribution#74]
With support for PHP8 in Flow, we get "false positives":

    Method Neos\Flow\Reflection\MethodReflection::getAttributes does not exist
    Method Neos\Flow\Reflection\ClassReflection::getAttributes does not exist
    Method Neos\Flow\Reflection\PropertyReflection::getAttributes does not exist

An update to `vimeo/psalm` is needed, but 4.9.3 triggers a bunch of new errors due to new/stricter reporting. Thus that is a task on it's own…

**Comment by kdambekalns** [comment]
Note: The development collection also declares a dependency on Psalm, that needs to be kept in sync!

**Comment by kdambekalns** [comment]
See https://github.com/neos/flow-development-collection/issues/2515

**Comment by albe** [comment]
Maybe we should indeed just run psalm with highest PHP version instead of lowest. The premise originally was "it should all work correctly with minimal requirements", but then we can't code forwards-compatible without psalm errors.

**Comment by kdambekalns** [comment]
But IIRC _those_ errors were gone locally with the latest Psalm even on PHP 7.4…

**Comment by albe** [comment]
Hm, yeah, probably psalm fixed that on their side then. So, no matter if we change to run psalm on another PHP version, upgrading is due...
